name: Lint Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - develop
permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reusable Setup
        uses: ./.github/actions/setup
        with:
          bun_version: "latest"

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: "commitlint.config.ts"
          failOnWarnings: true
