name: Publish to NPM

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged && startsWith(github.head_ref, 'changeset-release/')
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Reusable Setup
        uses: ./.github/actions/setup
        with:
          bun_version: "latest"

      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
