name: Publish to NPM

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'changeset-release/')
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Reusable Setup
        uses: ./.github/actions/setup
        with:
          bun_version: "latest"

      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-sync-pr:
    name: Create Sync PR
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'changeset-release/')
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: ⬇️ Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: "develop"
          fetch-depth: 0

      - name: Create PR from develop to main
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync main with develop"
          title: "Release: Sync main with latest changes"
          body: "This PR was automatically created to sync the `main` branch with the latest changes in `develop` after a successful package publish."
          base: "main"
          branch: "auto-gen-sync-develop-to-main"
          delete-branch: true
